### ISSUE TITLE
institutions in alphabetical order

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#12]
please put institutions in alphabetical order when adding school

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This one is fixed for your information

**Comment by drewrehfeld** [comment]
@asimshahzadmjc happy about this !! :)

![bitmoji](https://render.bitstrips.com/v2/cpanel/10117671-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)
