### ISSUE TITLE
forgot password link

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#13]
add forgot password link to login page and include steps for updating password

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is updated. Please verify.

**Comment by drewrehfeld** [comment]
@asimshahzadmjc this only gives a new password, not updating password, but this will work for now. i will provide designs

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Forgot password means one wants to reset password so the current mechanism in place is correct.
Where as for reset password I am thinking about having a profile page on dashboard from where a person can do profile specific items like updating profile picture, updating password etc.

**Comment by drewrehfeld** [comment]
yes, that should be the case, but i am saying update password when it is forgotten, not reset. but your solution should work fine, too.

**Comment by drewrehfeld** [comment]
@asimshahzadmjc this is working great, but please see my other issue about how it doesn't work in the alert
