### ISSUE TITLE
add school link

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#14]
there should be a link in the sidebar underneath existing schools "add school"

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is completed for your information

**Comment by drewrehfeld** [comment]
@asimshahzadmjc can you put this above the `<hr />` 

<img width="239" alt="screen shot 2017-09-13 at 1 53 15 pm" src="https://user-images.githubusercontent.com/19864464/30400279-3501b322-988b-11e7-9ebe-b3ab86372da3.png">

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is updated for your information.

**Comment by drewrehfeld** [comment]
@asimshahzadmjc confirmed :)
