### ISSUE TITLE
no modal for update profile picture

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#17]
i'll provide designs

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Please provide design for this one 
![bitmoji](https://render.bitstrips.com/v2/cpanel/10187861-320838475_2-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by drewrehfeld** [comment]
<img width="1217" alt="screen shot 2017-09-25 at 11 18 49 am" src="https://user-images.githubusercontent.com/19864464/30824225-b0ee7284-a1e3-11e7-97e7-4fb9abf5c41c.png">
@asimshahzadmjc  here is the design with the ability to update password

**Comment by drewrehfeld** [comment]
@asimshahzadmjc This is very bad, but this is what I did:

` 
                    <div id="tab_control_conntainer" style="margin-top: -20px">
                        <div class="tab-content">
                            <div id="alert-notification"></div>
                            <div class="tab-pane active" id="news" role="tabpanel">
                                <form enctype="multipart/form-data" method="POST" onsubmit="return addnewsfeed()">
                                    <div id="modal_profile_pic" class="modal fade">
    
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Update Profile Picture</h4>
            </div>
            <div class="modal-body">
                    <form id="wpua-edit-69" class="wpua-edit" action="" method="post" enctype="multipart/form-data">
                <div class="wpua-edit-container">
      <h3 style="margin-bottom: 18px">Profile</h3>
<hr />
	<div style="margin-left: 20px">
      <h4 style="margin-bottom: 30px; margin-top: 30px">Picture</h4>        <input type="hidden" name="wp-user-avatar" id="wp-user-avatar-existing" value="261" />
          
      </p>
      <p id="wpua-upload-messages-existing">
      </p>
        <div id="wpua-images-existing" class="" style="margin-bottom: 20px; margin-left: 10px">
      <p id="wpua-preview-existing" style="; margin-left: 10px">
        <img src="http://drakesnotes.com/wp-content/uploads/2017/04/prof-pic-300x200-1-300x200.jpg" alt="" />
        <span class="description">Original Size</span>
      </p>
      <p id="wpua-thumbnail-existing" style="margin-left: 30px">
        <img src="http://drakesnotes.com/wp-content/uploads/2017/04/prof-pic-300x200-1-150x150.jpg" style="border-radius: 50%" alt="" />
        <span class="description">Thumbnail</span>
      </p>
          </div>
          <div class="well" style="max-width: 290px; margin-left: 20px">
          <p id="wpua-upload-button-existing">
        <input name="wpua-file" id="wpua-file-existing" type="file" />
        <br />
        <button type="submit" class="btn btn-primary btn-md" id="wpua-upload-existing" name="submit" value="Upload">Upload</button>
</p>
</div>
</div>            <hr />
        <form class="form-horizontal" role="form">
          <div class="form-group">
            <div class="col-md-5">
            <h4 style="margin-bottom: 30px">Update Password</h4>             
              <input class="form-control" type="text" value="Old Password" style="margin-bottom: 10px; margin-left: 20px">
              <input class="form-control" type="text" value="New Password" style="margin-bottom: 10px; margin-left: 20px">
              <input class="form-control" type="text" value="Confirm New Password" style="margin-bottom: 10px; margin-left: 20px">

            </div>
            <div class="col-md-12">
            <input type="hidden" name="wpua_action" value="update" />
      <input type="hidden" name="user_id" id="user_id" value="69" />
      <input type="hidden" id="_wpnonce" name="_wpnonce" value="09559c8072" /><input type="hidden" name="_wp_http_referer" value="/my-desk/?id=1023" />      <p class="submit pull-right"><input type="submit" name="submit" id="submit" class="btn btn-success" value="Update"  />
      </div>
          </div>
      </form>

            </p>    </form>
              

              </div>

                                 </form>
                             </div>
                        </div>`

**Comment by asimshahzadmjc** [comment]
@drewrehfeld  Ready for testing

**Comment by drewrehfeld** [comment]
@asimshahzadmjc thanks :)![bitmoji](https://render.bitstrips.com/v2/cpanel/9319680-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)
