### ISSUE TITLE
formatting of comments

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#19]
currently, the post and reply fields are html; this should not be the case. the format that a user enters in the post or reply should works, as is. specifically, the user should be able to line break.

**Comment by drewrehfeld** [comment]
This is the #1 highest priority of anything @asimshahzadmjc

**Comment by asimshahzadmjc** [comment]
@drewrehfeld  Ready for testing

**Comment by drewrehfeld** [comment]
@asimshahzadmjc ![bitmoji](https://render.bitstrips.com/v2/cpanel/10221996-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)
