### ISSUE TITLE
delete gradebook items

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#2]
instructor should be able to delete gradebook items

**Comment by asimshahzadmjc** [comment]
@drewrehfeld You mean individual students grade deletion?

**Comment by drewrehfeld** [comment]
@asimshahzadmjc no, i mean an entire item, as i was asking in my email. you can just add an x next to the edit button and then a modal that says "Are you sure you want to delete this assignment?" 

<img width="952" alt="screen shot 2017-09-13 at 1 51 31 pm" src="https://user-images.githubusercontent.com/19864464/30400213-009e045a-988b-11e7-8e0e-f6fe4c6a1e44.png">

**Comment by drewrehfeld** [comment]
@asimshahzadmjc can this be done ASAP?

**Comment by asimshahzadmjc** [comment]
Yes it will be done tomorrow.

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is completed and uploaded. If a grade has a quiz related to that that quiz will be deleted along side grade. 
Please do check this one out and let me know in case you see any issue

**Comment by drewrehfeld** [comment]
completed :)
