### ISSUE TITLE
quiz time limit

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#24]
user should be able to set time limit for quiz as number of minutes

**Comment by asimshahzadmjc** [comment]
@drewrehfeld ready for testing

**Comment by drewrehfeld** [comment]
@asimshahzadmjc You can delete all of the information other than the title and the time remaining. can you do this soon? also, please add some space between the radio button and the text of the answer,  5px

Before
<img width="362" alt="screen shot 2017-09-21 at 2 06 10 pm" src="https://user-images.githubusercontent.com/19864464/30718887-5fa5595c-9ed6-11e7-8fbb-df3dcba54a03.png">

After
<img width="233" alt="screen shot 2017-09-21 at 2 10 05 pm" src="https://user-images.githubusercontent.com/19864464/30719034-e33f443a-9ed6-11e7-8254-7030e08f90cc.png">

**Comment by asimshahzadmjc** [comment]
@drewrehfeld  Ready for testing

**Comment by drewrehfeld** [comment]
@asimshahzadmjc don't allow minutes to go to next line

<img width="376" alt="screen shot 2017-09-28 at 2 56 20 pm" src="https://user-images.githubusercontent.com/19864464/30992167-5866955c-a45d-11e7-8a18-008728239316.png">

**Comment by asimshahzadmjc** [comment]
@drewrehfeld  Ready for testing

**Comment by drewrehfeld** [comment]
looks good :)

![bitmoji](https://render.bitstrips.com/v2/cpanel/9635657-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)
