### ISSUE TITLE
What should be the name of the site?

### ISSUE THREAD

**Issue by asimshahzadmjc** [drewrehfeld/opened#32]
Is it OpenEd from now on or Drakes Notes?
![bitmoji](https://render.bitstrips.com/v2/cpanel/10222574-320838475_2-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by drewrehfeld** [comment]
I don't know! @asimshahzadmjc 

![bitmoji](https://render.bitstrips.com/v2/cpanel/8810031-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by drewrehfeld** [comment]
@asimshahzadmjc edsimply.com i have the URL in dreamhost now
