### ISSUE TITLE
sidebar menu not working on mobile

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#33]
the entire sidebar menu is functioning as the "sign out" button... so the user cannot select any courses or schools. see screenshot.

![img_0013](https://user-images.githubusercontent.com/19864464/30663201-b640b226-9dfe-11e7-9087-abea91c865c6.PNG)

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is fixed for your information.

**Comment by drewrehfeld** [comment]
@asimshahzadmjc confirmed
