### ISSUE TITLE
title of quiz should be bold

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#41]
when a quiz is created, the title currently does not appear. the title should appear bold above the description in the same way as it does in creating a task.

**Comment by asimshahzadmjc** [comment]
@drewrehfeld  Ready for testing

**Comment by drewrehfeld** [comment]
Swag! @asimshahzadmjc 

![bitmoji](https://render.bitstrips.com/v2/cpanel/10219371-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)
