### ISSUE TITLE
? question mark on alerts

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#43]
the alerts should have X, but they are show question ? mark right now

<img width="1090" alt="screen shot 2017-09-25 at 11 01 27 am" src="https://user-images.githubusercontent.com/19864464/30826234-a8b0ccdc-a1ea-11e7-8664-46f546c19d97.png">

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Ready for testing

**Comment by drewrehfeld** [comment]
@asimshahzadmjc confirmed!

![bitmoji](https://render.bitstrips.com/v2/cpanel/7496923-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)
