### ISSUE TITLE
please remove grades

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#46]
please remove these grade entries i requested, or complete the requirement that allows me to delete them

course: PHIL 1 Fall 2017
grades: 
Quiz 1 8/21/2017
Quiz 1 8/23/2017

**Comment by asimshahzadmjc** [comment]
@drewrehfeld  ready for testing. Grade has been removed. Requirement is in progress

**Comment by drewrehfeld** [comment]
@asimshahzadmjc thanks :)
