### ISSUE TITLE
something weird happening with replies

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#47]
@asimshahzadmjc for some reason the reply action is duplicating. see below:

<img width="939" alt="screen shot 2017-10-03 at 2 58 36 pm" src="https://user-images.githubusercontent.com/19864464/31151267-8828a78e-a84b-11e7-8e97-96613609ab13.png">
<img width="939" alt="screen shot 2017-10-03 at 2 58 20 pm" src="https://user-images.githubusercontent.com/19864464/31151269-88337db2-a84b-11e7-8620-bc1a47dc6b99.png">
<img width="938" alt="screen shot 2017-10-03 at 2 57 32 pm" src="https://user-images.githubusercontent.com/19864464/31151268-88290c10-a84b-11e7-8f57-d2baae96544c.png">

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is fixed for your information

**Comment by drewrehfeld** [comment]
@asimshahzadmjc confirmed
