### ISSUE TITLE
two instructors for one course?

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#51]
can there be two instructors in one course? for zuventurez pitch, i want yuli perez (yperez@apu.edu) to also be an instructor for the course

**Comment by drewrehfeld** [comment]
can you do this ASAP? the two instructor should be yperez@apu.edu and the second will be zuventurez@apu.edu

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is not that much straight forward. Will let you know once this gets completed. Trying to complete it ASAP

**Comment by asimshahzadmjc** [comment]
@drewrehfeld  Both instructor will be able to manage each others content?

**Comment by drewrehfeld** [comment]
@asimshahzadmjc yes

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Expected to complete this one latest by tomorrow.

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This one is completed and uploaded to the server. Have made you instrcutor as well so that you can test that out. Once you are sure then will remove you from instructors.

Currently the server seems to be down. You will be able to test it as soon it comes back online,

**Comment by drewrehfeld** [comment]
ok great @asimshahzadmjc
