### ISSUE TITLE
change url to edsimply.com

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#53]
you will see this in dreamhost

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Now the redirection is properly setup the site is accessible using the new url. What should be the site name?
Drakesnotes or EdSimply or OpenED

**Comment by drewrehfeld** [comment]
EdSimply @asimshahzadmjc can you change this throughout the site ASAP? thanks!

**Comment by drewrehfeld** [comment]
@asimshahzadmjc i have changed some of these files, so please don't overwrite and can you please check that i got them all

**Comment by asimshahzadmjc** [comment]
@drewrehfeld You did it right. So I am closing this one for now 

![bitmoji](https://render.bitstrips.com/v2/cpanel/10120168-320838475_2-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Also to let you know have made the site name dynamic so that we can update from wp-admin and that is reflected on home page/ school and course page.
