### ISSUE TITLE
essay question option in quizzes

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#54]
i need this option available by wednesday this week. 

instructor should be able to grade the submissions also.

@asimshahzadmjc i will provide some designs tomorrow

**Comment by asimshahzadmjc** [comment]
@drewrehfeld For this issue this is something that will involve ability to recheck the quiz answers per user and then grade them accordingly.

**Comment by drewrehfeld** [comment]
Yes. in another program, it looks like the following. this requirement is not top priority within next day. this should be ready for an exam i must give on thursday. it doesn't have to look exactly like this, but just to give you an idea.

this is me creating the question


![screen shot 2017-10-09 at 11 41 58 am](https://user-images.githubusercontent.com/19864464/31353392-4a66c624-ace7-11e7-8468-302f1a99f98a.png)


this is the student answering the question


![screen shot 2017-10-09 at 11 42 21 am](https://user-images.githubusercontent.com/19864464/31353386-47456298-ace7-11e7-902f-2412829aa7ff.png)

**Comment by drewrehfeld** [comment]
@asimshahzadmjc are you close on this??

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Expected to get the instructors end completed along with the student end for taking the quiz.
As far as evaluation is concerned that may take a bit of time although trying to get through that today as well.
Once the above mentioned ends are completed you will be able to atleast give the quiz and students will be able to take that as well

**Comment by asimshahzadmjc** [comment]
@drewrehfeld the first part is completed i-e 
1) The instructor can create a quiz with Essay type question
2) The student can take the quiz and answer the essay question
3) The student will see Result Awaiting for those quizes which has at least one essay question and has not been evaluated yet
4) Instructor will be able to see Evaluate quiz button in front of quiz  on grades listing page to evaluate the essay questions.

Pending item is to give ability to instructor to evaluate the essay type of answers. It will be completed by tomorrow.

**Comment by drewrehfeld** [comment]
@asimshahzadmjc testing now :)

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is completed for your information. Please do check that out and let me know if you like that. You will have Evaluate button infront of quiz which will be visible until you have not evaluated all the students.
![bitmoji](https://render.bitstrips.com/v2/cpanel/10187861-320838475_2-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by drewrehfeld** [comment]
@asimshahzadmjc i like this :)![bitmoji](https://render.bitstrips.com/v2/cpanel/7681590-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)

i'll give you some updates in a bit
