### ISSUE TITLE
CAPTCHA on sign up page

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#55]
we need to add captcha to the sign up page. i am getting a lot of fake users :)

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is in place

**Comment by drewrehfeld** [comment]
@asimshahzadmjc ![bitmoji](https://render.bitstrips.com/v2/cpanel/7638212-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by drewrehfeld** [comment]
@asimshahzadmjc can you get rid of facebook login too? just for now

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Yes I did removed FB login as well
