### ISSUE TITLE
style issue on comment thread

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#61]
Something weird has happened with the spacing on posts on the newsfeed

current style:

![screen shot 2017-11-01 at 10 18 30 vm](https://user-images.githubusercontent.com/19864464/32287409-f620117e-beed-11e7-83d1-cf6b9e2e1b86.png)

what it should look like:

![screen shot 2017-11-01 at 10 18 33 vm](https://user-images.githubusercontent.com/19864464/32287402-f0149d04-beed-11e7-9a6c-b6a0f078c342.png)

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This is fixed

**Comment by drewrehfeld** [comment]
looks good @asimshahzadmjc ![bitmoji](https://render.bitstrips.com/v2/cpanel/843d8074-e7bc-409c-aeb1-2caf9f50dbf9-f6abd641-7266-4209-872a-e94ecd5793fe-v1.png?transparent=1&palette=1&width=246)
