### ISSUE TITLE
add comments to quizzes

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#63]
add a box underneath the quiz score for the instructor to add comments that the student can read
![screen shot 2018-02-12 at 10 36 17](https://user-images.githubusercontent.com/19864464/36113129-b157edca-0fe0-11e8-9d1a-26a26afe75be.png)

**Comment by drewrehfeld** [comment]
@asimshahzadmjc can this be done soon, as well?

**Comment by asimshahzadmjc** [comment]
@drewrehfeld Will try and complete this one tomorrow for you.

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This one is completed. Please review :)
