### ISSUE TITLE
make quizzes a "page"

### ISSUE THREAD

**Issue by drewrehfeld** [drewrehfeld/opened#7]
quizzes should load within the page wrapper, not as a modal

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This one is completed

**Comment by drewrehfeld** [comment]
@asimshahzadmjc i see this one is done, but the "return to course" button takes the user to the wrong course. in "Phil 1 Fa 2017", i took a quiz and the "return to course" button took me to "PHIL 1"

**Comment by asimshahzadmjc** [comment]
@drewrehfeld This issue is fixed

**Comment by drewrehfeld** [comment]
@asimshahzadmjc ![bitmoji](https://render.bitstrips.com/v2/cpanel/10155970-174733767_4-s1-v1.png?transparent=1&palette=1&width=246)
